version: "3.9"

services:

  mongodb:
    image: mongo
    container_name: dbProjet
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  api:
    build: .
    container_name: apiProjet
    ports:
      - '80:80'
    volumes:
      - ./app:/app
