version: "3.6"

services:
  api:
    build: .
    container_name: apiProjet
    env_file:
      - .env
    ports:
      - '8080:80'
    volumes:
      - ./app:/app/app
  
  mongodb:
    image: mongo
    container_name: mongoProjet
    ports:
      - '27017:27017'
    volumes:
      - 'projetdata:/data/db'

volumes:
  projetdata:
